// const weapons = [
//   {
//     "name": "Battleaxe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+3",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/axes/axe-battle.webp"
//   },
//   {
//     "name": "Warhammer",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D12+3",
//     "burden": "2H",
//     "feature": "Heavy (-1 to Agility)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/hammers/hammer-war-rounding.webp"
//   },
//   {
//     "name": "Greatsword",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+3",
//     "burden": "2H",
//     "feature": "Massive (-1 Agility, roll one extra damage die and drop the lowest)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/greatsword-crossguard-engraved-green.webp"
//   },
//   {
//     "name": "Mace",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D8+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/maces/mace-spiked-simple.webp"
//   },
//   {
//     "name": "Shortsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8",
//     "burden": "1H",
//     "feature": "Reliable (+1 to attack rolls with this weapon)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/shortsword-guard-brown.webp"
//   },
//   {
//     "name": "Longsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+3",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/sword-guard-purple.webp"
//   },
//   {
//     "name": "Cutlass",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D8+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/scimitar-guard-brown.webp"
//   },
//   {
//     "name": "Rapier",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D8",
//     "burden": "1H",
//     "feature": "Quick (Mark a Stress to attack an additional target in range. )",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/rapier_0.webp"
//   },
//   {
//     "name": "Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/daggers/dagger-black.webp"
//   },
//   {
//     "name": "Quarterstaff",
//     "traitName": "Instinct",
//     "range": "MELEE",
//     "damage": "D10+3",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "inst",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-simple.webp"
//   },
//   {
//     "name": "Halberd",
//     "traitName": "Strength",
//     "range": "VERY_CLOSE",
//     "damage": "D8+2",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/polearms/halberd-worn-steel.webp"
//   },
//   {
//     "name": "Shortbow",
//     "traitName": "Agility",
//     "range": "FAR",
//     "damage": "D6+3",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/shortbow-arrows-black.webp"
//   },
//   {
//     "name": "Crossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/crossbows/crossbow-simple-black.webp"
//   },
//   {
//     "name": "Longbow",
//     "traitName": "Agility",
//     "range": "VERY FAR",
//     "damage": "D6+3",
//     "burden": "2H",
//     "feature": "Cumbersome (-1 to Evasion)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/longbow-recurve-leather-brown.webp"
//   },
//   {
//     "name": "Arcane Gauntlets",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+3",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/fist/fist-knuckles-brass.webp"
//   },
//   {
//     "name": "Hallowed Axe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/axes/axe-battle-simple-black.webp"
//   },
//   {
//     "name": "Hand Runes",
//     "traitName": "Instinct",
//     "range": "VERY CLOSE",
//     "damage": "D10",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/skills/melee/unarmed-punch-fist-blue.webp"
//   },
//   {
//     "name": "Glowing Rings",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D10+2",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "agi",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/equipment/finger/ring-band-engraved-teal.webp"
//   },
//   {
//     "name": "Shortstaff",
//     "traitName": "Instinct",
//     "range": "CLOSE",
//     "damage": "D8+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-simple-spiral-grey.webp"
//   },
//   {
//     "name": "Wand",
//     "traitName": "Knowledge",
//     "range": "FAR",
//     "damage": "D6+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-gem-blue.webp"
//   },
//   {
//     "name": "Dualstaff",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D6+3",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-spiked.webp"
//   },
//   {
//     "name": "Returning Blade",
//     "traitName": "Finesse",
//     "range": "CLOSE",
//     "damage": "D8+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/sword-hooked-worn.webp"
//   },
//   {
//     "name": "Scepter",
//     "traitName": "Presence",
//     "range": "FAR",
//     "damage": "D6",
//     "burden": "2H",
//     "feature": "Versatile (Presence Melee - d10)",
//     "type": "mag",
//     "trait": "prs",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-carved-stone-shard.webp"
//   },
//   {
//     "name": "Greatstaff",
//     "traitName": "Knowledge",
//     "range": "VERY FAR",
//     "damage": "D6",
//     "burden": "2H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 0,
//     "isEquipped": false,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-ornate-blue-jewel.webp"
//   },
//   {
//     "name": "Improved Battleaxe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+6",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/axes/axe-battle-blackened.webp"
//   },
//   {
//     "name": "Improved Warhammer",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D12+6",
//     "burden": "2H",
//     "feature": "Heavy (-1 to Agility)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/hammers/hammer-double-engraved.webp"
//   },
//   {
//     "name": "Improved Greatsword",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+6",
//     "burden": "2H",
//     "feature": "Massive (-1 Agility, roll one extra damage die and drop the lowest)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/greatsword-guard-gem-blue.webp"
//   },
//   {
//     "name": "Improved Mace",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/maces/mace-round-spiked-grey.webp"
//   },
//   {
//     "name": "Improved Cutlass",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D8+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/scimitar-guard-gold.webp"
//   },
//   {
//     "name": "Improved Longsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+6",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/sword-guard-engraved.webp"
//   },
//   {
//     "name": "Improved Shortsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+3",
//     "burden": "1H",
//     "feature": "Reliable (+1 to attack rolls with this weapon)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/sword-guard-red-jewel.webp"
//   },
//   {
//     "name": "Improved Rapier",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D8+3",
//     "burden": "1H",
//     "feature": "Quick (Mark a Stress to attack an additional target in range. )",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/rapier_1.webp"
//   },
//   {
//     "name": "Improved Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/daggers/dagger-curved-blue.webp"
//   },
//   {
//     "name": "Improved Quarterstaff",
//     "traitName": "Instinct",
//     "range": "MELEE",
//     "damage": "D10+6",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "inst",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-ornate-hook.webp"
//   },
//   {
//     "name": "Improved Halberd",
//     "traitName": "Strength",
//     "range": "VERY CLOSE",
//     "damage": "D8+5",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/polearms/halberd-crescent-small-spiked.webp"
//   },
//   {
//     "name": "Improved Shortbow",
//     "traitName": "Agility",
//     "range": "FAR",
//     "damage": "D6+6",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/shortbow-leather.webp"
//   },
//   {
//     "name": "Improved Crossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/crossbows/crossbow-purple.webp"
//   },
//   {
//     "name": "Improved Longbow",
//     "traitName": "Agility",
//     "range": "VERY FAR",
//     "damage": "D6+6",
//     "burden": "2H",
//     "feature": "Cumbersome (-1 to Evasion)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/longbow-leather-green.webp"
//   },
//   {
//     "name": "Gilded Falchion",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+4",
//     "burden": "1H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/greatsword-guard-gold-worn.webp"
//   },
//   {
//     "name": "Urok Shortsword",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+3",
//     "burden": "1H",
//     "feature": "Deadly (When you do Severe damage, deal one extra HP. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/scimitar-bone.webp"
//   },
//   {
//     "name": "Steelforged Halberd",
//     "traitName": "Strength",
//     "range": "VERY CLOSE",
//     "damage": "D8+4",
//     "burden": "2H",
//     "feature": "Scary (Successful attacks also deal an extra Stress. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/polearms/halberd-crescent-steel.webp"
//   },
//   {
//     "name": "Bladed Whip",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D8+3",
//     "burden": "1H",
//     "feature": "Quick (Mark a Stress to make an attack against two targets in range of you. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/whip_1.webp"
//   },
//   {
//     "name": "War Scythe",
//     "traitName": "Finesse",
//     "range": "VERY CLOSE",
//     "damage": "D8+5",
//     "burden": "2H",
//     "feature": "Reliable (+1 on attack rolls with this weapon. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/sickles/scythe-wrapped-red.webp"
//   },
//   {
//     "name": "Knuckle Blades",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+6",
//     "burden": "2H",
//     "feature": "Brutal (For every 8 rolled on a damage die, roll an extra d8 of damage. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/fist/claws-engraved-grey.webp"
//   },
//   {
//     "name": "Greatbow",
//     "traitName": "Strength",
//     "range": "FAR",
//     "damage": "D6+6",
//     "burden": "2H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/bow-ornamental-gold-blue.webp"
//   },
//   {
//     "name": "Blunderbuss",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+6",
//     "burden": "1H",
//     "feature": "Reloading (Roll 1d6 after the attack. On a 1, you must use an action to reload your weapon before you can fire it again. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/guns/gun-blunderbuss-bronze.webp"
//   },
//   {
//     "name": "Finehair Bow",
//     "traitName": "Agility",
//     "range": "VERY FAR",
//     "damage": "D6+5",
//     "burden": "2H",
//     "feature": "Reliable (+1 on attack rolls with this weapon. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/longbow-recurve-skull-brown.webp"
//   },
//   {
//     "name": "Improved Arcane Gauntlets",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+6",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/equipment/hand/gauntlet-cuffed-steel-blue.webp"
//   },
//   {
//     "name": "Improved Hallowed Axe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/axes/axe-broad-chipped-glow-yellow.webp"
//   },
//   {
//     "name": "Improved Hand Runes",
//     "traitName": "Instinct",
//     "range": "VERY CLOSE",
//     "damage": "D10+3",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/skills/melee/unarmed-punch-fist-white.webp"
//   },
//   {
//     "name": "Improved Glowing Rings",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D10+5",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/equipment/finger/ring-cabochon-engraved-purple.webp"
//   },
//   {
//     "name": "Improved Shortstaff",
//     "traitName": "Instinct",
//     "range": "CLOSE",
//     "damage": "D8+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-engraved-wood.webp"
//   },
//   {
//     "name": "Improved Wand",
//     "traitName": "Knowledge",
//     "range": "FAR",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-gem-green.webp"
//   },
//   {
//     "name": "Improved Dualstaff",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D6+6",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-carved-pink.webp"
//   },
//   {
//     "name": "Improved Returning Blade",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D8+4",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/sword-hooked-engraved.webp"
//   },
//   {
//     "name": "Improved Scepter",
//     "traitName": "Presence",
//     "range": "FAR",
//     "damage": "D6+3",
//     "burden": "2H",
//     "feature": "Versatile (Presence Melee - d10+3)",
//     "type": "mag",
//     "trait": "prs",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-gem-teal.webp"
//   },
//   {
//     "name": "Improved Greatstaff",
//     "traitName": "Knowledge",
//     "range": "VERY FAR",
//     "damage": "D6+3",
//     "burden": "2H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest.",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-ornate-cross.webp"
//   },
//   {
//     "name": "Hammer of Exota",
//     "traitName": "Instinct",
//     "range": "MELEE",
//     "damage": "D8+6",
//     "burden": "2H",
//     "feature": "Eruptive (When you hit a creature in Melee, each Very Close enemy must make a React (5) roll or take half damage as well. )",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/hammers/hammer-double-engraved-gold.webp"
//   },
//   {
//     "name": "Casting Sword",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+4",
//     "burden": "2H",
//     "feature": "Versatile (Knowledge Far - d6+3)",
//     "type": "mag",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/greatsword-guard-split-eyes.webp"
//   },
//   {
//     "name": "Bonded Staff",
//     "traitName": "Knowledge",
//     "range": "FAR",
//     "damage": "D6+4",
//     "burden": "2H",
//     "feature": "Reliable (+1 on any attack rolls with this weapon. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-forest-hooked.webp"
//   },
//   {
//     "name": "Devouring Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+4",
//     "burden": "1H",
//     "feature": "Scary (Successful attacks also deal a stress. )",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/daggers/dagger-double-skull-pink.webp"
//   },
//   {
//     "name": "Elder Bow",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D6+4",
//     "burden": "2H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/longbow-gold-pink.webp"
//   },
//   {
//     "name": "Wand of Enthrallment",
//     "traitName": "Presence",
//     "range": "FAR",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "Persuasive (Mark stress before rolling Presence to add +2 to the result. )",
//     "type": "mag",
//     "trait": "prs",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-simple-eye.webp"
//   },
//   {
//     "name": "Ego Blade",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D12+4",
//     "burden": "1H",
//     "feature": "Pompous (Must have a Presence score of 0 or less to use this weapon. )",
//     "type": "mag",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/greatsword-sheathed.webp"
//   },
//   {
//     "name": "Scepter of Elias",
//     "traitName": "Presence",
//     "range": "FAR",
//     "damage": "D6+3",
//     "burden": "1H",
//     "feature": "Invigorating (When you make a successful attack, roll a d4. On a 4, clear a stress. )",
//     "type": "mag",
//     "trait": "prs",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-crook-yellow.webp"
//   },
//   {
//     "name": "Yutari Bloodbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+4",
//     "burden": "2H",
//     "feature": "Brutal (For every 10 rolled on a damage die, roll an additional d10 of damage. )",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/yutari.webp"
//   },
//   {
//     "name": "Advanced Battleaxe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+9",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/axes/axe-double-engraved-blue.webp"
//   },
//   {
//     "name": "Advanced Warhammer",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D12+9",
//     "burden": "2H",
//     "feature": "Heavy (-1 to Agility)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/warhammer.webp"
//   },
//   {
//     "name": "Advanced Shortsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+6",
//     "burden": "1H",
//     "feature": "Reliable (+1 to attack rolls with this weapon)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/sword-guard-embossed-green.webp"
//   },
//   {
//     "name": "Advanced Rapier",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D8+6",
//     "burden": "1H",
//     "feature": "Quick (Mark stress to attack an additional target in range. )",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/rapier_2.webp"
//   },
//   {
//     "name": "Advanced Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+7",
//     "burden": "1H",
//     "feature": "-",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/dagger_2.webp"
//   },
//   {
//     "name": "Advanced Quarterstaff",
//     "traitName": "Instinct",
//     "range": "MELEE",
//     "damage": "D10+9",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "inst",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/qs_2.webp"
//   },
//   {
//     "name": "Advanced Longsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+9",
//     "burden": "2H",
//     "feature": "-",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/sword-hilt-steel-green.webp"
//   },
//   {
//     "name": "Advanced Greatsword",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+6",
//     "burden": "2H",
//     "feature": "Massive (-1 Agility, roll one extra damage die and drop the lowest)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/greatsword-flamberge.webp"
//   },
//   {
//     "name": "Advanced Mace",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D8+7",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/maces/mace-round-spiked-black.webp"
//   },
//   {
//     "name": "Advanced Cutlass",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D8+7",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/cutlass_2.webp"
//   },
//   {
//     "name": "Advanced Halberd",
//     "traitName": "Strength",
//     "range": "VERY CLOSE",
//     "damage": "D8+8",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/polearms/halberd-crescent-glowing.webp"
//   },
//   {
//     "name": "Advanced Shortbow",
//     "traitName": "Agility",
//     "range": "FAR",
//     "damage": "D6+9",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/shortbow-recurve-blue.webp"
//   },
//   {
//     "name": "Advanced Crossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+7",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/crossbows/crossbow-heavy-black.webp"
//   },
//   {
//     "name": "Advanced Longbow",
//     "traitName": "Agility",
//     "range": "VERY FAR",
//     "damage": "D6+9",
//     "burden": "2H",
//     "feature": "Cumbersome (-1 to Evasion)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/bow-recurve-black.webp"
//   },
//   {
//     "name": "Bravesword",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D12+7",
//     "burden": "2H",
//     "feature": "Dense (-1 to Agility & +3 to Severe Damage Threshold)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/bravesword.webp"
//   },
//   {
//     "name": "Flickerfly Blade",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+5",
//     "burden": "1H",
//     "feature": "Sharpwing (Add your Agility score to this weapon's damage roll. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/flickering.webp"
//   },
//   {
//     "name": "Meridian Cutlass",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D10+5",
//     "burden": "1H",
//     "feature": "Dueling (Take advantage on attack rolls when there is nobody else in Close range. )",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/meridan.webp"
//   },
//   {
//     "name": "Labrys Axe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+7",
//     "burden": "2H",
//     "feature": "Protective (Add +1 to your Armor score. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/labrys.webp"
//   },
//   {
//     "name": "Hell’s Hammer",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+7",
//     "burden": "2H",
//     "feature": "Devastating (Mark stress before your attack roll to use d20s as your damage dice instead. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/hellhammer.webp"
//   },
//   {
//     "name": "Retractable Saber",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D10+7",
//     "burden": "1H",
//     "feature": "Retractable (Blade can be hidden in hilt to avoid recognition as a weapon. )",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/retract.webp"
//   },
//   {
//     "name": "Double Flail",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D10+8",
//     "burden": "2H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/maces/flail-triple-grey.webp"
//   },
//   {
//     "name": "Talon Blades",
//     "traitName": "Finesse",
//     "range": "CLOSE",
//     "damage": "D10+7",
//     "burden": "2H",
//     "feature": "Brutal (For every 10 rolled on a damage die, roll an additional d10 of damage. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/talon.webp"
//   },
//   {
//     "name": "Spiked Bow",
//     "traitName": "Agility",
//     "range": "VERY FAR",
//     "damage": "D6+7",
//     "burden": "2H",
//     "feature": "Versatile (Agility Melee - d12+5)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/spiked.webp"
//   },
//   {
//     "name": "Black Powder Revolver",
//     "traitName": "Finesse",
//     "range": "VERY FAR",
//     "damage": "D6+6",
//     "burden": "1H",
//     "feature": "Reloading (Roll 1d6 after the attack. On a 1, you must use an action to reload your weapon before you can fire it again. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/guns/gun-pistol-flintlock-metal.webp"
//   },
//   {
//     "name": "Advanced Arcane Gauntlets",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+9",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/arcane_2.webp"
//   },
//   {
//     "name": "Advanced Hallowed Axe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+7",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/hallow_2.webp"
//   },
//   {
//     "name": "Advanced Hand Runes",
//     "traitName": "Instinct",
//     "range": "VERY CLOSE",
//     "damage": "D10+6",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/hr_2.webp"
//   },
//   {
//     "name": "Advanced Glowing Rings",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D10+8",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/equipment/finger/ring-band-gold-purple.webp"
//   },
//   {
//     "name": "Advanced Shortstaff",
//     "traitName": "Instinct",
//     "range": "CLOSE",
//     "damage": "D8+7",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/staves/staff-ornate-purple.webp"
//   },
//   {
//     "name": "Advanced Wand",
//     "traitName": "Knowledge",
//     "range": "FAR",
//     "damage": "D6+7",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-gem-violet.webp"
//   },
//   {
//     "name": "Advanced Returning Blade",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D8+7",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/return_2.webp"
//   },
//   {
//     "name": "Advanced Dualstaff",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D6+9",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/dual_2.webp"
//   },
//   {
//     "name": "Advanced Scepter",
//     "traitName": "Presence",
//     "range": "FAR",
//     "damage": "D6+6",
//     "burden": "2H",
//     "feature": "Versatile (Presence Melee - d10+4)",
//     "type": "mag",
//     "trait": "prs",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/sceptor_2.webp"
//   },
//   {
//     "name": "Advanced Greatstaff",
//     "traitName": "Knowledge",
//     "range": "VERY FAR",
//     "damage": "D6+6",
//     "burden": "2H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/greatstaff_2.webp"
//   },
//   {
//     "name": "Mage Orb",
//     "traitName": "Knowledge",
//     "range": "FAR",
//     "damage": "D6+7",
//     "burden": "1H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/mage_orb.webp"
//   },
//   {
//     "name": "Firestaff",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D6+7",
//     "burden": "2H",
//     "feature": "Burn (For every damage dice that rolls an 8, deal a stress. )",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/firestaff.webp"
//   },
//   {
//     "name": "Body Runes",
//     "traitName": "Knowledge",
//     "range": "VERY CLOSE",
//     "damage": "D20+4",
//     "burden": "1H",
//     "feature": "Painful (Mark stress every time you roll damage on an attack with this weapon. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/body_runes.webp"
//   },
//   {
//     "name": "Ghostblade",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D10+7",
//     "burden": "1H",
//     "feature": "Otherworldly (You can choose whether to do Physical or Magic damage. )",
//     "type": "any",
//     "trait": "prs",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/ghost_blade.webp"
//   },
//   {
//     "name": "Axe of Fortunis",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+8",
//     "burden": "2H",
//     "feature": "Lucky (Spend a Stress on a failure to reroll your attack and take the new result. )",
//     "type": "mag",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/fortunis.webp"
//   },
//   {
//     "name": "Gilded Bow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+7",
//     "burden": "2H",
//     "feature": "Self-Correcting (Any 1’s rolled on the damage dice may be treated as 8’s instead. )",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/bows/bow-ornamental-gold-blue.webp"
//   },
//   {
//     "name": "Blessed Anlace",
//     "traitName": "Instinct",
//     "range": "MELEE",
//     "damage": "D10+6",
//     "burden": "1H",
//     "feature": "Healing (During downtime, automatically heal 1 hit point. )",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/blessed.webp"
//   },
//   {
//     "name": "Ilmari’s Blunderbuss",
//     "traitName": "Finesse",
//     "range": "VERY FAR",
//     "damage": "D6+6",
//     "burden": "1H",
//     "feature": "Reloading (Roll 1d6 after the attack. On a 1, you must use an action to reload your weapon before you can fire it again. )",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/weapons/guns/gun-blunderbuss-gold.webp"
//   },
//   {
//     "name": "Widogast Pendant",
//     "traitName": "Knowledge",
//     "range": "CLOSE",
//     "damage": "D10+5",
//     "burden": "1H",
//     "feature": "Timebender (You may choose the target of your attack after making your attack roll. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 2,
//     "isSecondary": false,
//     "img": "icons/equipment/neck/pendant-silver-red.webp"
//   },
//   {
//     "name": "Legendary Battleaxe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+12",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/axe_3.webp"
//   },
//   {
//     "name": "Legendary Warhammer",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D12+12",
//     "burden": "2H",
//     "feature": "Heavy (-1 to Agility)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/wh_3.webp"
//   },
//   {
//     "name": "Legendary Shortsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+9",
//     "burden": "1H",
//     "feature": "Reliable (+1 to attack rolls with this weapon)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/short_3.webp"
//   },
//   {
//     "name": "Legendary Longsword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+12",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/long_3.webp"
//   },
//   {
//     "name": "Legendary Greatsword",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+9",
//     "burden": "2H",
//     "feature": "Massive (-1 Agility, roll one extra damage die and drop the lowest)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "icons/weapons/swords/greatsword-crossguard-embossed-gold.webp"
//   },
//   {
//     "name": "Legendary Rapier",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D8+9",
//     "burden": "1H",
//     "feature": "Quick (Mark a Stress to attack an additional target in range. )",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/rapier_3.webp"
//   },
//   {
//     "name": "Legendary Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+10",
//     "burden": "1H",
//     "feature": "-",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/dagger_3.webp"
//   },
//   {
//     "name": "Legendary Quarterstaff",
//     "traitName": "Instinct",
//     "range": "MELEE",
//     "damage": "D10+12",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/qs_3.webp"
//   },
//   {
//     "name": "Legendary Mace",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D8+9",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/mace_3.webp"
//   },
//   {
//     "name": "Legendary Cutlass",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+10",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/cutlass_3.webp"
//   },
//   {
//     "name": "Legendary Halberd",
//     "traitName": "Strength",
//     "range": "VERY CLOSE",
//     "damage": "D8+11",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/halberd_3.webp"
//   },
//   {
//     "name": "Legendary Shortbow",
//     "traitName": "Agility",
//     "range": "FAR",
//     "damage": "D6+12",
//     "burden": "2H",
//     "feature": "",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/sb_3.webp"
//   },
//   {
//     "name": "Legendary Crossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+10",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/cb_3.webp"
//   },
//   {
//     "name": "Legendary Longbow",
//     "traitName": "Agility",
//     "range": "VERY FAR",
//     "damage": "D6+12",
//     "burden": "2H",
//     "feature": "Cumbersome (-1 to Evasion)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/lb_3.webp"
//   },
//   {
//     "name": "Double-Sided Sword",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D10+9",
//     "burden": "2H",
//     "feature": "Quick (Mark a Stress to attack an additional target in range. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/doubleside.webp"
//   },
//   {
//     "name": "Curved Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+9",
//     "burden": "1H",
//     "feature": "Serrated (Any 1’s rolled on the damage dice count as 11 points of damage. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/curved.webp"
//   },
//   {
//     "name": "Swinging Ropeblade",
//     "traitName": "Presence",
//     "range": "CLOSE",
//     "damage": "D8+9",
//     "burden": "2H",
//     "feature": "Grappling (Spend Hope on a successful attack to temporarily make the target Restrained, or pull them into melee with you. )",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/rope_blade.webp"
//   },
//   {
//     "name": "Extended Polearm",
//     "traitName": "Finesse",
//     "range": "VERY CLOSE",
//     "damage": "D8+10",
//     "burden": "2H",
//     "feature": "Long (Can target all enemies in a line within range with your attack)",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/extended.webp"
//   },
//   {
//     "name": "Sledge Axe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D12+13",
//     "burden": "2H",
//     "feature": "Destructive (-1 to Agility, all Very Close enemies mark a Stress on a successful attack)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/sledge.webp"
//   },
//   {
//     "name": "Impact Gauntlet",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+11",
//     "burden": "1H",
//     "feature": "Concussive (Spend Hope on a successful attack to launch the target into Far range. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/impact.webp"
//   },
//   {
//     "name": "Aantari Bow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+11",
//     "burden": "2H",
//     "feature": "Reliable (+1 on any attack rolls with this weapon. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/aantari.webp"
//   },
//   {
//     "name": "Ricochet Axes",
//     "traitName": "Agility",
//     "range": "FAR",
//     "damage": "D6+11",
//     "burden": "2H",
//     "feature": "Bouncing (Spend any amount of Stress to hit that many targets in range with the attack. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/ricochet.webp"
//   },
//   {
//     "name": "Hand Cannon",
//     "traitName": "Finesse",
//     "range": "VERY FAR",
//     "damage": "D6+12",
//     "burden": "1H",
//     "feature": "Reloading (Roll 1d6 after the attack. On a 1, you must use an action to reload your weapon before you can fire it again. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "icons/weapons/guns/rifle-white.webp"
//   },
//   {
//     "name": "Legendary Arcane Gauntlets",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+12",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/arcane_3.webp"
//   },
//   {
//     "name": "Legendary Hallowed Axe",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+10",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/hallow_3.webp"
//   },
//   {
//     "name": "Legendary Hand Runes",
//     "traitName": "Instinct",
//     "range": "VERY CLOSE",
//     "damage": "D10+9",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/runes_3.webp"
//   },
//   {
//     "name": "Legendary Glowing Rings",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D10+11",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/rings_3.webp"
//   },
//   {
//     "name": "Legendary Shortstaff",
//     "traitName": "Instinct",
//     "range": "CLOSE",
//     "damage": "D8+10",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/shortstaff_3.webp"
//   },
//   {
//     "name": "Legendary Wand",
//     "traitName": "Knowledge",
//     "range": "FAR",
//     "damage": "D6+10",
//     "burden": "1H",
//     "feature": "",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "icons/weapons/wands/wand-carved-fire.webp"
//   },
//   {
//     "name": "Legendary Dualstaff",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D8+10",
//     "burden": "2H",
//     "feature": "",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/dual_3.webp"
//   },
//   {
//     "name": "Legendary Scepter",
//     "traitName": "Presence",
//     "range": "FAR",
//     "damage": "D6+9",
//     "burden": "2H",
//     "feature": "Versatile (Presence Melee - d10+6)",
//     "type": "mag",
//     "trait": "prs",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/scepter_3.webp"
//   },
//   {
//     "name": "Legendary Greatstaff",
//     "traitName": "Knowledge",
//     "range": "VERY FAR",
//     "damage": "D6+9",
//     "burden": "2H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/greatstaff_3.webp"
//   },
//   {
//     "name": "Sword of Light & Flame",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D10+11",
//     "burden": "2H",
//     "feature": "Penetrating (Cuts through solid material. )",
//     "type": "mag",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/lightflame.webp"
//   },
//   {
//     "name": "Siphoning Gauntlets",
//     "traitName": "Presence",
//     "range": "MELEE",
//     "damage": "D10+9",
//     "burden": "2H",
//     "feature": "Lifestealing (On a successful attack, roll a d6. On a 6, heal a hit point or clear a Stress. )",
//     "type": "mag",
//     "trait": "prs",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "icons/equipment/hand/gauntlet-armored-leather-teal-orange.webp"
//   },
//   {
//     "name": "Midas Scythe",
//     "traitName": "Knowledge",
//     "range": "MELEE",
//     "damage": "D10+9",
//     "burden": "2H",
//     "feature": "Greedy (You may spend one handful of gold to increase your proficiency by +1 on a damage roll. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/midas.webp"
//   },
//   {
//     "name": "Floating Bladeshards",
//     "traitName": "Instinct",
//     "range": "CLOSE",
//     "damage": "D8+9",
//     "burden": "1H",
//     "feature": "Powerful (Roll one extra damage die and drop the lowest. )",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/blade_shards.webp"
//   },
//   {
//     "name": "Thistlebow",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D6+13",
//     "burden": "2H",
//     "feature": "Reliable (+1 on any attack rolls with this weapon. )",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/thistle.webp"
//   },
//   {
//     "name": "Wand of Essek",
//     "traitName": "Knowledge",
//     "range": "FAR",
//     "damage": "D8+13",
//     "burden": "1H",
//     "feature": "Timebender (-1 to Agility. You may choose the target of your attack after making your attack roll. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/essek.webp"
//   },
//   {
//     "name": "Magus Revolver",
//     "traitName": "Finesse",
//     "range": "VERY FAR",
//     "damage": "D6+13",
//     "burden": "1H",
//     "feature": "Reloading (Roll 1d6 after the attack. On a 1, you must use an action to reload your weapon before you can fire it again. )",
//     "type": "mag",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "icons/weapons/guns/gun-pistol-flintlock.webp"
//   },
//   {
//     "name": "Bloodstaff",
//     "traitName": "Instinct",
//     "range": "FAR",
//     "damage": "D20+7",
//     "burden": "2H",
//     "feature": "Painful (Mark a Stress every time you roll damage on an attack with this weapon. )",
//     "type": "mag",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/bloodstaff.webp"
//   },
//   {
//     "name": "Fusion Gloves",
//     "traitName": "Knowledge",
//     "range": "VERY FAR",
//     "damage": "D6+9",
//     "burden": "2H",
//     "feature": "Bonded (Add your Level to the damage result. )",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 3,
//     "isSecondary": false,
//     "img": "systems/daggerheart/assets/icons/weapons/fusion.webp"
//   },
//   {
//     "name": "Round Shield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D4",
//     "burden": "1H",
//     "feature": "Protective (Add +2 to your armor score. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 0,
//     "isSecondary": true,
//     "img": "icons/equipment/shield/buckler-wooden-boss-brown.webp"
//   },
//   {
//     "name": "Tower Shield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D6",
//     "burden": "1H",
//     "feature": "Barrier (Add +4 to your armor score, -2 to Evasion)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 0,
//     "isSecondary": true,
//     "img": "icons/equipment/shield/wardoor-wooden-boss-brown.webp"
//   },
//   {
//     "name": "Small Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8",
//     "burden": "1H",
//     "feature": "Paired (+2 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 0,
//     "isSecondary": true,
//     "img": "icons/weapons/daggers/dagger-curved-guard.webp"
//   },
//   {
//     "name": "Saber",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8",
//     "burden": "1H",
//     "feature": "Paired (+2 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 0,
//     "isSecondary": true,
//     "img": "icons/weapons/swords/scimitar-blue.webp"
//   },
//   {
//     "name": "Whip",
//     "traitName": "Presence",
//     "range": "VERY CLOSE",
//     "damage": "D6",
//     "burden": "1H",
//     "feature": "Whipcrack (Mark a Stress to scatter enemies in Melee into Close range)",
//     "type": "phy",
//     "trait": "prs",
//     "tier": 0,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/whip_2.webp"
//   },
//   {
//     "name": "Grappler",
//     "traitName": "Finesse",
//     "range": "CLOSE",
//     "damage": "D6",
//     "burden": "1H",
//     "feature": "Hook (On a successful attack, you may also pull the target into Melee with you)",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 0,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/grappler.webp"
//   },
//   {
//     "name": "Hand Crossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+1",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 0,
//     "isSecondary": true,
//     "img": "icons/weapons/crossbows/handcrossbow-black.webp"
//   },
//   {
//     "name": "Improved Round Shield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D4+2",
//     "burden": "1H",
//     "feature": "Protective (+3 to Armor Score. )",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "icons/equipment/shield/buckler-wooden-boss-brown.webp"
//   },
//   {
//     "name": "Improved Tower Shield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D6+2",
//     "burden": "1H",
//     "feature": "Barrier (+5 to Armor Score, -2 to Evasion)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "icons/equipment/shield/targe-boss-steel-brown.webp"
//   },
//   {
//     "name": "Improved Small Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+2",
//     "burden": "1H",
//     "feature": "Paired (+3 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "icons/weapons/daggers/dagger-curved-gold.webp"
//   },
//   {
//     "name": "Improved Saber",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+2",
//     "burden": "1H",
//     "feature": "Paired (+3 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "icons/weapons/swords/scimitar-guard-red.webp"
//   },
//   {
//     "name": "Improved Hand Crossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+3",
//     "burden": "1H",
//     "feature": "",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "icons/weapons/crossbows/handcrossbow-green.webp"
//   },
//   {
//     "name": "Improved Whip",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D6+2",
//     "burden": "1H",
//     "feature": "Whipcrack (Mark stress to scatter enemies in Melee into Close range)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/whip_2.webp"
//   },
//   {
//     "name": "Spiked Shield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D6+2",
//     "burden": "1H",
//     "feature": "Double Duty (+2 to Armor score, +1 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/spiked_shield.webp"
//   },
//   {
//     "name": "Parrying Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D6+2",
//     "burden": "1H",
//     "feature": "Parry (On an attack against you, roll this weapon’s damage dice. If any match the attacker’s, they are removed before damage is totalled. )",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/parry_dagger.webp"
//   },
//   {
//     "name": "Returning Axe",
//     "traitName": "Agility",
//     "range": "CLOSE",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "-",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 1,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/returning_axe.webp"
//   },
//   {
//     "name": "Advanced Round\nShield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D4+4",
//     "burden": "1H",
//     "feature": "Protective (+4 to Armor Score)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/ars_2.webp"
//   },
//   {
//     "name": "Advanced Tower\nShield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "Barrier (+6 to Armor Score, -2 to Evasion)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/tower_2.webp"
//   },
//   {
//     "name": "Advanced Small\nDagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+4",
//     "burden": "1H",
//     "feature": "Paired (+4 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/sd_2.webp"
//   },
//   {
//     "name": "Advanced Saber",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+4",
//     "burden": "1H",
//     "feature": "Paired (+4 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/saber_2.webp"
//   },
//   {
//     "name": "Advanced Hand\nCrossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "—",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/hb_2.webp"
//   },
//   {
//     "name": "Advanced Whip",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "Whipcrack (Mark stress to scatter enemies in Melee into Close range)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/whip_3.webp"
//   },
//   {
//     "name": "Buckler",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D4+4",
//     "burden": "1H",
//     "feature": "Deflecting (On an incoming attack, you may spend an armor slot to boost your Evasion score by your Armor score. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/buckler.webp"
//   },
//   {
//     "name": "Powered Gauntlet",
//     "traitName": "Knowledge",
//     "range": "CLOSE",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "Charged Attack (Mark stress to increase proficiency by +1 on Primary Weapon attack)",
//     "type": "mag",
//     "trait": "knwl",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/powered.webp"
//   },
//   {
//     "name": "Hand Sling",
//     "traitName": "Finesse",
//     "range": "VERY FAR",
//     "damage": "D6+4",
//     "burden": "1H",
//     "feature": "Versatile (Finesse Close - d8+4)",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 2,
//     "isSecondary": true,
//     "img": "icons/weapons/slings/slingshot-wood.webp"
//   },
//   {
//     "name": "Legendary Round Shield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D4+6",
//     "burden": "1H",
//     "feature": "Protective (+5 to Armor Score)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/lrs_3.webp"
//   },
//   {
//     "name": "Legendary Tower Shield",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D4+6",
//     "burden": "1H",
//     "feature": "Barrier (+7 to Armor Score, -2 to Evasion)",
//     "type": "phy",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/lts_3.webp"
//   },
//   {
//     "name": "Legendary Small Dagger",
//     "traitName": "Finesse",
//     "range": "MELEE",
//     "damage": "D8+6",
//     "burden": "1H",
//     "feature": "Paired (+5 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/lsd_3.webp"
//   },
//   {
//     "name": "Legendary Saber",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D8+6",
//     "burden": "1H",
//     "feature": "Paired (+5 to Primary Weapon damage in Melee)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "icons/weapons/swords/scimitar-guard-wood.webp"
//   },
//   {
//     "name": "Legendary Crossbow",
//     "traitName": "Finesse",
//     "range": "FAR",
//     "damage": "D6+7",
//     "burden": "1H",
//     "feature": "—",
//     "type": "phy",
//     "trait": "fin",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/cb_4.webp"
//   },
//   {
//     "name": "Legendary Whip",
//     "traitName": "Agility",
//     "range": "VERY CLOSE",
//     "damage": "D6+6",
//     "burden": "1H",
//     "feature": "Whipcrack (Mark stress to scatter enemies in Melee into Close range)",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/whip_4.webp"
//   },
//   {
//     "name": "Braveshield",
//     "traitName": "Agility",
//     "range": "MELEE",
//     "damage": "D4+6",
//     "burden": "1H",
//     "feature": "Sheltering (Using an armor slot reduces damage for you and all allies in Melee with you. )",
//     "type": "phy",
//     "trait": "agi",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/brave.webp"
//   },
//   {
//     "name": "Knuckle Claws",
//     "traitName": "Strength",
//     "range": "MELEE",
//     "damage": "D6+6",
//     "burden": "1H",
//     "feature": "Doubled Up (When you make an attack with your Primary Weapon, you also apply that roll to another enemy in range of this weapon. )",
//     "type": "mag",
//     "trait": "str",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/handclaws.webp"
//   },
//   {
//     "name": "Primer Shard",
//     "traitName": "Instinct",
//     "range": "VERY CLOSE",
//     "damage": "-",
//     "burden": "1H",
//     "feature": "Locked On (On a successful attack with this weapon against a target, the next hit with your Primary Weapon automatically hits that target. )",
//     "type": "-",
//     "trait": "inst",
//     "tier": 3,
//     "isSecondary": true,
//     "img": "systems/daggerheart/assets/icons/weapons/primer.webp"
//   }
// ];

// Hooks.on("ready", async () => {
//   console.log("ready");
//   const [weaponFolder] = await Folder.createDocuments([
//     { name: "Weapons", type: "Item" },
//   ]);

//   // // const [testFolder] = await Folder.createDocuments([
//   // //   { name: "LMAO REAL?", type: "Item", parent: domainFolder.id },
//   // // ]);

//   const weaponFolderArray = [
//     { name: "Starting Weapons", type: "Item", parent: weaponFolder.id },
//     { name: "Tier 1", type: "Item", parent: weaponFolder.id },
//     { name: "Tier 2", type: "Item", parent: weaponFolder.id },
//     { name: "Tier 3", type: "Item", parent: weaponFolder.id },
//     { name: "Secondary Weapons", type: "Item", parent: weaponFolder.id },
   
//   ];

//   const weaponTiers = await Folder.createDocuments(weaponFolderArray);

//   const weaponTiersObj = weaponTiers.map(fold => fold.id)

//   weapons.forEach((item) => {
//     Item.create({
//       type: "weapon",
//       name: `${item.isSecondary ? `[${item.tier}]` : ""} ${item.name}`,
//       system: { ...item, isEquipped: false},
//       img: item.img,
//       folder: item.isSecondary ? weaponTiersObj[4] : weaponTiersObj[item.tier],
//     });
//   }); 
// });

